# Generated by Django 3.2.16 on 2022-12-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahtooei_messenger', '0002_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='inactive_date',
            field=models.DateTimeField(null=True),
        ),
    ]
