# Generated by Django 3.2.16 on 2022-12-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahtooei_messenger', '0003_alter_chatuser_inactive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='delete_date',
            field=models.DateTimeField(null=True),
        ),
    ]
