# Generated by Django 3.2.16 on 2022-12-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kahtooei_messenger', '0004_alter_chatgroup_delete_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipient',
            old_name='recive_date',
            new_name='receive_date',
        ),
    ]
