# Generated by Django 3.2.16 on 2022-12-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kahtooei_messenger', '0005_rename_recive_date_userrecipient_receive_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('group', 'user')},
        ),
    ]
